name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          # Тут ми додаємо опцію для викачування сабмодулів
        submodules: 'recursive'

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bogi2/laravel-dock-php-one:$(date +%s)

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: docker push bogi2/laravel-dock-php-one:$(date +%s)

    - name: Build the Dev Docker image
      run: docker build . --file Dockerfile1.dev --tag bogi2/laravel-dock-node-t:$(date +%s)
    - name: Push the Dev Docker image
      run: docker push bogi2/laravel-dock-node-t:$(date +%s)
