name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        # Тут ми додаємо опцію для викачування сабмодулів
        submodules: 'recursive'
        
    - name: Calculate unique tag
      id: prep
      run: echo "UNIQUE_TAG=$(date +%s)" >> $GITHUB_ENV
        
    - name: Build the laravel-dock-php-one
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/laravel-dock-php-one:${{ env.UNIQUE_TAG }}
        
    - name: Build the laravel-dock-node-t
      run: docker build . --file Dockerfile1 --tag ${{ secrets.DOCKER_USERNAME }}/laravel-dock-node-t:${{ env.UNIQUE_TAG }}
        
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push the laravel-dock-php-one
      run: docker push ${{ secrets.DOCKER_USERNAME }}/laravel-dock-php-one:${{ env.UNIQUE_TAG }}
        
    - name: Push the laravel-dock-node-t
      run: docker push ${{ secrets.DOCKER_USERNAME }}/laravel-dock-node-t:${{ env.UNIQUE_TAG }}
