name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Calculate unique tag
      id: prep
      run: echo "UNIQUE_TAG=$(date +%s)" >> $GITHUB_ENV
        
    - name: Build the php-composer
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/php-composer:${{ env.UNIQUE_TAG }}
        
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push the php-composer
      run: docker push ${{ secrets.DOCKER_USERNAME }}/php-composer:${{ env.UNIQUE_TAG }}