name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bogi2/laravel-dock-php-one:$(date +%s)

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
    
      run: docker push bogi2/laravel-dock-php-one:$(date +%s)

    - name: Build the Dev Docker image
      run: docker build . --file Dockerfile1.dev --tag bogi2/laravel-dock-node-t:$(date +%s)
    - name: Push the Dev Docker image
      run: docker push bogi2/laravel-dock-node-t:$(date +%s)